[package]
name = "memo"
version = "0.1.0"
authors = ["Nathan Kolpa <nathan@kolpa.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
sha2 = "0.9.5"
